{
  "language": "python",
  "python": "3.6",
  "install": [
    "pip install -r requirements.txt"
  ],
  "script": "nosetests",
  "after_success": [
    "codecov"
  ],
  "group": "stable",
  "dist": "precise",
  "os": "linux"
}
